"""Remove retracted again

Revision ID: 25ee14ba6d86
Revises: 6237f4cde293
Create Date: 2026-08-10 11:58:15.595480

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel's string columns autogenerate as `sqlmodel.sql.sqltypes.AutoString`,
# so migration scripts need this importable even though it looks unused.
# The submodule is imported explicitly (rather than just `import sqlmodel`)
# so that type checkers can see where `AutoString` comes from.
import sqlmodel.sql.sqltypes
from alembic import op

revision: str = "25ee14ba6d86"
down_revision: str | None = "6237f4cde293"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.drop_column("retracted")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.add_column(sa.Column("retracted", sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
