"""drop the uniqueness constraint on dataset facets

Revision ID: b8b5b4587e4a
Revises: dfd25558499d
Create Date: 2026-08-05 12:17:59.698786

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel's string columns autogenerate as `sqlmodel.sql.sqltypes.AutoString`,
# so migration scripts need this importable even though it looks unused.
# The submodule is imported explicitly (rather than just `import sqlmodel`)
# so that type checkers can see where `AutoString` comes from.
import sqlmodel.sql.sqltypes
from alembic import op

revision: str = "b8b5b4587e4a"
down_revision: str | None = "dfd25558499d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_dataset_facets"), type_="unique")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration"""
    # Note that this downgrade can fail, and that is deliberate.
    # Once the constraint is gone, the database is allowed to hold rows
    # that describe the same data under different IDs,
    # and putting the constraint back cannot invent an answer
    # to which of those rows should survive.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_dataset_facets"),
            [
                "variable",
                "processing_id",
                "experiment",
                "model",
                "variant_label",
                "reporting_interval",
                "grid_label",
                "project",
                "institution",
            ],
        )

    # ### end Alembic commands ###
