"""Add project specific ID and retracted to Dataset

Revision ID: 696f84386291
Revises: ac846e40d991
Create Date: 2026-08-10 11:24:30.939274

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel's string columns autogenerate as `sqlmodel.sql.sqltypes.AutoString`,
# so migration scripts need this importable even though it looks unused.
# The submodule is imported explicitly (rather than just `import sqlmodel`)
# so that type checkers can see where `AutoString` comes from.
import sqlmodel.sql.sqltypes
from alembic import op

revision: str = "696f84386291"
down_revision: str | None = "ac846e40d991"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "id_project_specific",
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("retracted", sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.drop_column("retracted")
        batch_op.drop_column("id_project_specific")

    # ### end Alembic commands ###
