"""make id_project_specific unique

Revision ID: 2c9d34ba583d
Revises: 25ee14ba6d86
Create Date: 2026-08-10 12:07:20.559520

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

# SQLModel's string columns autogenerate as `sqlmodel.sql.sqltypes.AutoString`,
# so migration scripts need this importable even though it looks unused.
# The submodule is imported explicitly (rather than just `import sqlmodel`)
# so that type checkers can see where `AutoString` comes from.
import sqlmodel.sql.sqltypes
from alembic import op

revision: str = "2c9d34ba583d"
down_revision: str | None = "25ee14ba6d86"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            batch_op.f("uq_dataset_id_project_specific"), ["id_project_specific"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Undo this migration"""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("dataset", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_dataset_id_project_specific"), type_="unique"
        )

    # ### end Alembic commands ###
