"""
Searching ESGF

Queries can be written in whichever vocabulary suits the user (see [esmporium.query][])
and search results are (will be) automatically translated into the database
(see [esmporium.db][]).
"""

from esmporium.search.apis import (
    LimitOutOfRangeError,
    NoFacetValuesReturned,
    NoSearchResultNumberOfMatchesReturned,
    Request,
    SearchAPI,
    SearchAPIESGF1Solr,
    SearchAPIESGF15BridgeSolr,
    SearchAPIESGFNGSTAC,
    UncompilableFacetPatternError,
)
from esmporium.search.check_query_values import (
    AllowedValues,
    CouldNotGetAllowedValuesError,
    FacetFinding,
    FindingKind,
    NoSourceWouldAnswerError,
    NotAFacetOfTheQueryError,
    ValueCheckOutcome,
    ValueReport,
    allowed_values_from_api,
    check_query_values,
    check_query_values_low,
    close_matches_difflib,
    compare_values,
    facets_the_user_set,
    values_set_for,
)
from esmporium.search.health import (
    SearchAPICall,
    SearchAPICallObserver,
    fan_out,
)
from esmporium.search.retry import build_transient_retrying
from esmporium.search.search import (
    DEFAULT_LIMIT,
    CouldNotSearchError,
    NoAPIWouldAnswerError,
    SearchAPIRequestError,
    SearchOutcome,
    fire,
    get_url,
    search,
)
from esmporium.search.search_api_facade import (
    DEFAULT_SEARCH_API_FACADES_BY_PROJECT,
    DEFAULT_SELECTOR,
    INBUILT_SEARCH_API_FACADE_STORE,
    OneProjectRequiredError,
    ProjectPrefixMismatchError,
    SearchAPIFacade,
    SearchAPIFacadeClassification,
    SearchAPIFacadeSelector,
    SearchAPIFacadeStore,
    SelectorOfferedNoAPIFacadeError,
    SolrCMIP5Parameters,
    SolrCMIP6Parameters,
    SolrCMIP7Parameters,
    STACCMIP5Parameters,
    STACCMIP6Parameters,
    STACCMIP7Parameters,
    STACParams,
    UnaskableFacetError,
    build_list_selector,
    build_project_list_selector,
    check_facets_askable,
    check_facets_expressible,
    native_facet_names,
    stac_collection,
    unexpressible_facets,
)

__all__ = [
    "DEFAULT_LIMIT",
    "DEFAULT_SEARCH_API_FACADES_BY_PROJECT",
    "DEFAULT_SELECTOR",
    "INBUILT_SEARCH_API_FACADE_STORE",
    "AllowedValues",
    "CouldNotGetAllowedValuesError",
    "CouldNotSearchError",
    "FacetFinding",
    "FindingKind",
    "LimitOutOfRangeError",
    "NoAPIWouldAnswerError",
    "NoFacetValuesReturned",
    "NoSearchResultNumberOfMatchesReturned",
    "NoSourceWouldAnswerError",
    "NotAFacetOfTheQueryError",
    "OneProjectRequiredError",
    "ProjectPrefixMismatchError",
    "Request",
    "STACCMIP5Parameters",
    "STACCMIP6Parameters",
    "STACCMIP7Parameters",
    "STACParams",
    "SearchAPI",
    "SearchAPICall",
    "SearchAPICallObserver",
    "SearchAPIESGF1Solr",
    "SearchAPIESGF15BridgeSolr",
    "SearchAPIESGFNGSTAC",
    "SearchAPIFacade",
    "SearchAPIFacadeClassification",
    "SearchAPIFacadeSelector",
    "SearchAPIFacadeStore",
    "SearchAPIRequestError",
    "SearchOutcome",
    "SelectorOfferedNoAPIFacadeError",
    "SolrCMIP5Parameters",
    "SolrCMIP6Parameters",
    "SolrCMIP7Parameters",
    "UnaskableFacetError",
    "UncompilableFacetPatternError",
    "ValueCheckOutcome",
    "ValueReport",
    "allowed_values_from_api",
    "build_list_selector",
    "build_project_list_selector",
    "build_transient_retrying",
    "check_facets_askable",
    "check_facets_expressible",
    "check_query_values",
    "check_query_values_low",
    "close_matches_difflib",
    "compare_values",
    "facets_the_user_set",
    "fan_out",
    "fire",
    "get_url",
    "native_facet_names",
    "search",
    "stac_collection",
    "unexpressible_facets",
    "values_set_for",
]
